### ISSUE TITLE
Mettre en place un metabase

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/vao#280]
L'équipe VAO a fait la demande d'un Metabase.
Discussion Mattermost: https://mattermost.fabrique.social.gouv.fr/default/pl/ez5qbjq4cibt5kwkkgo7nthdxr

#### Les étapes:
- [x] Mettre en place le Metabase (SRE)
- [x] Ajouter un cron pour faire créer les dump anonymisés (SRE)
- [ ] Ajouter un CNPG en prod sur lequel appliquer le dump anonymisé (VAO)

**Comment by achauve** [comment]
Après discussion avec l'équipe SRE : 
- [x] metabase sur le cluster de prod
- [ ] ajouter DB anonymisée sur la prod pour brancher sur metabase
