### ISSUE TITLE
Mise en place de PGAdmin

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/vao#281]
Mettre en place des PGAdmin (ou PGWeb) sur les environnement lié aux branches `preprod` et `main`

- [ ] Ajouter un PGAdmin pour la branche `preprod`
- [ ] Ajouter un PGAdmin pour la branche `main`
- [ ] Ajouter l'oauth devant chaque client PG

**Comment by gary-van-woerkens** [comment]
Si on utilisait pgweb au lieu de pagadmin, est-ce que ne pourrait pas être géré par les les devops du produit directement ? @achauve :)

https://github.com/SocialGouv/kontinuous/blob/5eddc5d9132c67a1137ea07d75c1a3ff65b737d9/plugins/fabrique/charts/pgweb/Chart.yaml#L1-L8

**Comment by matmut7** [comment]
À archiver pour le moment https://mattermost.fabrique.social.gouv.fr/default/pl/wi94p97xibgejmxnu8g6cxpzuw
